%\VignetteIndexEntry{Handling Modifications with MSnID}
%\VignetteDepends{BiocStyle, ggplot2}
%\VignetteKeywords{Documentation}
%\VignettePackage{MSnID}
\documentclass[11pt]{article}


<<style, eval=TRUE, echo=FALSE, results=tex>>=
BiocStyle::latex(use.unsrturl=FALSE)
@


\title{Handling Modifications with \Rpackage{MSnID}}
\author{Vladislav A. Petyuk}

\begin{document}
\SweaveOpts{concordance=TRUE, eval=TRUE, prefix.string=graphics}

\maketitle
\tableofcontents



\section{Introduction}
This vignette describes handling modifications of the peptides. Modifications
can be biologically-relevant and introduced after protein translation, thus 
\underline{p}ost-\underline{t}ranlational \underline{m}odifications or PTMs.
Modification can also be introduced as artifact during sample processing.
Here we call any modification, be that PTM or sample preparation artifact, as
modification.

\section{Quick Example}
Currently here is only a quick example, that also can be found as 
% \code{?map\_mod\_sites}.

<<eval=FALSE>>=
m <- MSnID(".")
mzids <- system.file("extdata","phospho.mzid.gz",package="MSnID")
m <- read_mzIDs(m, mzids)

# to know the present mod masses
report_mods(m)

# TMT modification
m <- add_mod_symbol(m, mod_mass="229.1629", symbol="#")
# alkylation
m <- add_mod_symbol(m, mod_mass="57.021463735", symbol="^")
# phosphorylation
m <- add_mod_symbol(m, mod_mass="79.966330925", symbol="*")

# show the mapping
head(unique(subset(psms(m), select=c("modification", "peptide_mod"))))

# read fasta for mapping modifications
fst_path <- system.file("extdata","for_phospho.fasta.gz",package="MSnID")
fst <- readAAStringSet(fst_path)
# to ensure names are the same as in accessions(m)
names(fst) <- sub("(^[^ ]*) .*$", "\1", names(fst))
# # mapping phosphosites
m <- map_mod_sites(m, fst, "accession", "peptide_mod", "*")

head(unique(subset(psms(m), select=c("accession", "peptide_mod", "SiteID"))))

# clean-up cache
unlink(".Rcache", recursive=TRUE)
@

\end{document}
